name: CI/CD - Azure ML (CLI)

on:
  push:
    branches: ["main"]
    paths:
      - "mlops/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  create-compute:
    uses: ./.github/workflows/create-compute.yml
    with:
      cluster_name: cpu-cluster
      size: Standard_DS11_v2
      min_instances: 0
      max_instances: 2
      resource_group: rboaro-rg
      workspace_name: AI_Studies
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  run-azureml-job:
    needs: create-compute
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI extension
        run: |
          az extension add -n ml -y
          az extension update -n ml

      - name: Submit Azure ML job
        run: |
          az ml job create \
            --file mlops/pipeline.yml \
            --resource-group rboaro-rg \
            --workspace-name AI_Studies
