$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

display_name: ci-cd-pipeline-smoke
experiment_name: ci-cd-smoke

code: ../mlops/src

command: >-
  python hello.py

environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

compute: azureml:cpu-cluster
